CREATE TABLE USER (
  uid      INT         AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) DEFAULT NULL,
  PASSWORD VARCHAR(20) DEFAULT NULL,
  nickname VARCHAR(20) DEFAULT NULL,
  email    VARCHAR(30) DEFAULT NULL,
  state    INT(11)     DEFAULT NULL,
  CODE     VARCHAR(64) DEFAULT NULL
)
  ENGINE = INNODB
  DEFAULT CHARSET = utf8